feat novo fluxo

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -36,7 +36,8 @@ jobs:
           push: true
           build-args: |
             BUILDKIT_INLINE_CACHE=1
-  Build-Database:
+
+  Test-Database:
     runs-on: ubuntu-latest
     needs: [Build-Dockerfile]
     steps:
@@ -89,36 +90,41 @@ jobs:
         
             echo "Creating database..."
             docker exec -i sqlserver sqlcmd -S localhost -U sa -P ${{ secrets.SQL_SERVER_PASSWORD }} -Q "CREATE DATABASE ContactKeeper;" || { echo "Failed to create database"; docker logs sqlserver; exit 1; }
-  Test-API:   
-      needs: [Build-Dockerfile]
-      steps:
-        - name: Run API container
-          run: |
+
+  Test-API:
+    runs-on: ubuntu-latest
+    needs: [Test-Database]
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+      - name: Run API container
+        run: |
             docker run --name contactkeeper \
               --network contactkeeper-network \
               -p 5000:5001 \
               -e "DatabaseSettings__${{ secrets.ENV_DEVOPS }}=Server=sqlserver,1433;Database=ContactKeeper;User Id=sa;Password=${{ secrets.SQL_SERVER_PASSWORD }};TrustServerCertificate=True;" \
               -d ${{ secrets.DOCKER_USERNAME }}/main-contactkeeper-api:latest
 
-        - name: Run tests and health check
-          env: ASPNETCORE_ENVIRONMENT: ${{ secrets.ENV_DEVOPS }}
-          run: |
-            echo "Waiting for API to initialize..."
-              for i in {1..30}; do
-                if curl -f ${{ secrets.API_URL }}/Health/HealthDataBase > /dev/null 2>&1; then
-                  echo "API is ready!"
-                  break
-                fi
-                echo "Waiting for API... ($i/5)"
-                sleep 2
-              done
-              if [ $i -eq 30 ]; then
-                echo "API failed to start"
-                docker logs contactkeeper
-                exit 1
-              fi
+      - name: Run tests and health check
+        env:
+          ASPNETCORE_ENVIRONMENT: ${{ secrets.ENV_DEVOPS }}
+        run: |
+          echo "Waiting for API to initialize..."
+          for i in {1..30}; do
+            if curl -f ${{ secrets.API_URL }}/Health/HealthDataBase > /dev/null 2>&1; then
+              echo "API is ready!"
+              break
+            fi
+            echo "Waiting for API... ($i/5)"
+            sleep 2
+          done
+          if [ $i -eq 30 ]; then
+            echo "API failed to start"
+            docker logs contactkeeper
+            exit 1
+          fi
 
-              dotnet test ./ContactKeeper.Test/ContactKeeper.Test.csproj --configuration Release --verbosity normal
+          dotnet test ./ContactKeeper.Test/ContactKeeper.Test.csproj --configuration Release --verbosity normal
 
 # name: ci-cd pipeline
 
