ok

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -39,15 +39,14 @@ jobs:
             --network contactkeeper-network \
             -e "ACCEPT_EULA=Y" \
             -e "MSSQL_SA_PASSWORD=${{ secrets.SQL_SERVER_PASSWORD }}" \
-            -p 1433:1433 \
-            --memory="2g" \
-            --cpus="1" \
+            -p 1433:1433 \         
             -d mcr.microsoft.com/mssql/server:2022-latest
-          if [ $? -ne 0 ]; then
-            echo "Failed to start SQL Server container"
-            docker logs sqlserver
-            exit 1
-          fi
+            
+            if [ $? -ne 0 ]; then
+              echo "Failed to start SQL Server container"
+              docker logs sqlserver
+              exit 1
+            fi
         
           echo "Installing mssql-tools..."
           docker exec sqlserver bash -c "apt-get update && \
